{{ if .Values.persistence.enabled }}
{{- $root := . -}}
{{ range $i, $e := until (atoi (quote $root.Values.replicaCount) | default 3) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $root.Release.Name }}-{{ $root.Values.service.name }}-{{ $i }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    type: {{ $root.Values.persistence.storageType }}
    app: {{ $root.Values.service.name }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  capacity:
    storage: {{ $root.Values.persistence.size }}
  accessModes:
    - {{ $root.Values.persistence.accessMode }}
  hostPath:
    path: {{ $root.Values.persistence.mountPath }}/{{ $root.Release.Name }}/{{ $root.Values.persistence.mountSubPath }}-{{$i}}
  persistentVolumeReclaimPolicy: {{ $root.Values.persistence.volumeReclaimPolicy }}
{{- if $root.Values.persistence.storageClass }}
{{- if (eq "-" $root.Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ $root.Values.persistence.storageClass }}"
{{- end }}
{{- end }}
{{ end }}
{{ end }}
